name: Mirror to gitee

on: [push, delete, create]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITGITEE }}
        with:
          source-repo: "git@github.com:ycvcb123/githubaction.git"
          destination-repo: "git@gitee.com:yezw/githubaction.git"
